[advisories]
ignore = [
  # As the rust community considers the paste crate 'done', we can safely ignore this warning.
  # see https://users.rust-lang.org/t/paste-alternatives/126787/2
  "RUSTSEC-2024-0436",
  # TODO find a suitable replacement for fxhash.
  "RUSTSEC-2025-0057",
  # TODO remove once newer versions of tracing-sbuscriber support colored logs again.
  "RUSTSEC-2025-0055",
  # TODO remove once `self_update` updates its dependency for `indicatif`.
  "RUSTSEC-2025-0119",
  # TODO remove once no longer lru 0.12.x is unsound via ratatui; upgrade ratatui when available
  "RUSTSEC-2026-0002",
  # TODO remove once we migrate away from bincode, or it becomes maintained again.
  "RUSTSEC-2025-0141",
  # TODO remove once termwiz/terminfo update to phf 0.13+, which drops the rand 0.8 dependency.
  "RUSTSEC-2026-0097",
]
